# Generated by Django 6.0.2 on 2026-05-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_sal', models.FloatField()),
                ('emp_dep', models.CharField(choices=[('hr', 'hr'), ('it', 'it'), ('sales', 'sales'), ('admin', 'admin')], max_length=30)),
                ('emp_mail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
