# Generated by Django 6.0.2 on 2026-05-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('emp_name', models.EmailField(max_length=254, unique=True)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
