# Generated by Django 6.0.2 on 2026-05-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_alter_employee_emp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
