# Generated by Django 6.0.2 on 2026-05-10 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_mail', models.EmailField(max_length=254)),
                ('emp_mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='enter 10 digits valid mobile number', regex='[6-9][0-9]{9}')])),
                ('emp_joindate', models.DateField()),
                ('emp_salary', models.FloatField()),
                ('emp_image', models.ImageField(blank=None, default=None, upload_to='images/')),
                ('emp_doc', models.FileField(blank=None, default=None, upload_to='files/')),
                ('emp_dep', models.CharField(choices=[('hr', 'hr'), ('sales', 'sales'), ('it', 'it'), ('admin', 'admin')], max_length=30)),
            ],
        ),
    ]
